### ISSUE TITLE
php5_fpm_pool should provide attribute listen_socket

### ISSUE THREAD

**Issue by estahn** [stajkowski/php5-fpm#11]
Currently it's only possible to configure php5-fpm in TCP mode. It would be great to be able to configure it to listen to sockets.

**Comment by stajkowski** [comment]
It absolutely does already.  Here is how you get it going:

php5_fpm_pool "example3sockets" do
    pool_user "fpm_user"
    pool_group "fpm_group"
    use_sockets true
    listen_socket "/var/run/phpfpm_example.sock"
    listen_owner "fpm_user"
    listen_group "fpm_group"
    listen_mode "0660"
    overwrite true
    action :create
    notifies :restart, "service[#{node["php_fpm"]["package"]}]", :delayed
end

Let me know if you have any issues with this!

**Comment by estahn** [comment]
@stajkowski Alright, i missed that. Thanks for pointing out.

**Comment by stajkowski** [comment]
No problem!  Let me know if you have any issues.
