### ISSUE TITLE
No such file or directory - /sbin/status

### ISSUE THREAD

**Issue by develnk** [stajkowski/php5-fpm#12]
Hello. I created new box with ubuntu server 15.04. Where i tried to install this cookbook i got error:
No such file or directory - /sbin/status

Additional info:

==> webserver: Resource Declaration:
==> webserver: ---------------------
==> webserver: # In /tmp/vagrant-chef/3c68afa41c272c080f6b05038c8e8f7f/cookbooks/php5-fpm/recipes/install.rb
==> webserver: 
==> webserver: 
==> webserver: 117: service node["php_fpm"]["package"] do
==> webserver: 
==> webserver: 118:     #Bug in 14.04 for service provider. Adding until resolved.
==> webserver: 
==> webserver: 119:     if (platform?('ubuntu') && node['platform_version'].to_f >= 14.04)
==> webserver: 120:         provider Chef::Provider::Service::Upstart
==> webserver: 121:     end
==> webserver: 122:     supports :start => true, :stop => true, :restart => true, :reload => true

==> webserver: Compiled Resource:
==> webserver: ------------------
==> webserver: # Declared in /tmp/vagrant-chef/3c68afa41c272c080f6b05038c8e8f7f/cookbooks/php5-fpm/recipes/install.rb:117:in `from_file'
==> webserver: 
==> webserver: service("php5-fpm") do
==> webserver: 
==> webserver:   provider Chef::Provider::Service::Upstart
==> webserver:   action [:enable, :start]
==> webserver:   supports {:start=>true, :stop=>true, :restart=>true, :reload=>true}
==> webserver:   retries 0
==> webserver: 
==> webserver:   retry_delay 2
==> webserver: 
==> webserver:   default_guard_interpreter :default
==> webserver:   service_name "php5-fpm"
==> webserver: 
==> webserver:   pattern "php5-fpm"
==> webserver:   declared_type :service
==> webserver: 
==> webserver:   cookbook_name :"php5-fpm"
==> webserver:   recipe_name "install"
==> webserver: end
==> webserver: 
==> webserver: 
==> webserver: [2015-05-05T07:34:47+06:00] INFO: Running queued delayed notifications before re-raising exception
==> webserver: [2015-05-05T07:34:47+06:00] ERROR: Running exception handlers
==> webserver: [2015-05-05T07:34:47+06:00] ERROR: Exception handlers complete
==> webserver: [2015-05-05T07:34:47+06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> webserver: [2015-05-05T07:34:47+06:00] ERROR: service[php5-fpm] (php5-fpm::install line 117) had an error: Errno::ENOENT: No such file or directory - /sbin/status
==> webserver: [2015-05-05T07:34:47+06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by stajkowski** [comment]
Awesome, this hasn't been tested yet against 15.04 but I will complete it and get it working again for this release.

**Comment by stajkowski** [comment]
Able to replicate. Fixing.

**Comment by stajkowski** [comment]
This was fixed with static provider on 14.04 only.  The issue now is that it appears to be a filed bug with systemd on vivid.  Here is what I get now:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1451346

I'll keep track of this but you may want to use 14.04 for now due to this particular bug.
