### ISSUE TITLE
Deprecated # character in pool config files

### ISSUE THREAD

**Issue by saintberry** [stajkowski/php5-fpm#15]
I'm seeing the following message in my application log files:

```
Comments starting with '#' are deprecated in Unknown on line 1 in file Unknown on line 0
```

I tracked this down to the comments that get put from the provider to create my custom pool configuration:

```
f.puts "###### Ping Status"
```

Could we please change all these to comments to the ; character:

```
f.puts ";;;;;; Ping Status"
```

This resolves these messages.

**Comment by saintberry** [comment]
Looks as though there is a PR fixing this issue: https://github.com/stajkowski/php5-fpm/pull/13. Can we get this merged / released?

**Comment by stajkowski** [comment]
Merged
