### ISSUE TITLE
Support for using sockets

### ISSUE THREAD

**Issue by iiro** [stajkowski/php5-fpm#5]
Hi,

and first of all - excellent stuff! :)

Have you had any thoughts about supporting sockets as well - in addition to IPv4...?

I guess it would enough to support directives listen and listen_backlog...

**Comment by stajkowski** [comment]
So from what I can tell, what I am missing is listen_backlog.  The listen directive is there but is broken up for ipv4.  I'll go ahead and add listen_socket as well and if listen_socket is stated, it will override ipv4 being set.

**Comment by iiro** [comment]
Hullo :)

Excellent - you are welcome dude! :)

I did it without the LWRP now - using attributes :)

**Comment by stajkowski** [comment]
Support for sockets in LWRP is now in 4.1.  Thanks!
