### ISSUE TITLE
Incompatible with Chef 11.10.4 and earlier

### ISSUE THREAD

**Issue by mike-spainhower** [stajkowski/php5-fpm#6]
Since the `0.3.3` version of this cookbook, the cookbook metadata has included attributes with `type` `boolean`.  This was not a valid `type` in Chef versions 11.10.4 and earlier (See https://github.com/opscode/chef/blob/11.10.4/lib/chef/cookbook/metadata.rb#L394).

The main reason this is a bummer is that AWS OpsWorks just happens to use Chef 11.10.4.  This results in the following when you try to converge:

```
[2015-01-08T19:40:18+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/php5-fpm into a Chef object: Option type must be equal to one of: string, array, hash, symbol!  You passed "boolean".
[2015-01-08T19:40:18+00:00] ERROR: #<NoMethodError: undefined method `to_hash' for nil:NilClass>
/opt/aws/opsworks/releases/20141216163306_33300020141216163306/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:85:in `block in get'
```

It is completely valid for this to be a `wontfix`, but I wanted you to be aware of this issue and document it for others that run into this.  A compatibility warning in the README may also be nice (happy to PR).

**Comment by stajkowski** [comment]
This fortunately is only for visual appeal in Chef Server. I can actually change the attribute type in Metadata without harming anything else in the cookbook.  I'll go ahead an change it to String as it doesn't really matter.

**Comment by mike-spainhower** [comment]
Cool.  Going back to `0.3.2` works in my recipe, so I am good either way.  Thanks!

**Comment by stajkowski** [comment]
I'll go ahead and do a 4.2 release really quick.  No reason not to use the latest and greatest!

**Comment by stajkowski** [comment]
Ok 4.2 is up with the change.  Let me know that you are good to go.

**Comment by mike-spainhower** [comment]
Works locally, but unfortunately using `kitchen-ec2` (which I use for testing in CI) I get

```
Chef::Exceptions::PrivateKeyMissing       
-----------------------------------       
I cannot read /tmp/kitchen/client.pem, which you told me to use to sign requests!       
    

Cookbook Trace:       
---------------       
/tmp/kitchen/cookbooks/hostupgrade/recipes/upgrade.rb:44:in `block (2 levels) in from_file'  
```

Which should only happen if a recipe is using the `search()` function AFAIK.  `hostupgrade` doesn't use that function, so I am stumped.

Regrettably I will just stay at `0.3.2` for now since it works for me locally, on CI, and in prod.  All the same much thanks for a quick turnaround on this issue! :love_hotel: 

Don't waste any time on it, but if you have any thoughts off the top of your head on mitigating this issue, I'd gladly upgrade to `4.2`.

Closing since the original issue is indeed fixed!

**Comment by stajkowski** [comment]
Yes, this is an issue.  Hostupgrade saves a node attribute and this throws the error.  Most people use chef-zero instead of chef-solo to fix the problem.

**Comment by mike-spainhower** [comment]
Yup, I use `chef-zero` locally, but I did not see an option in the `kirchen-ec2` provisioner to make it use zero also (I can see in its output that it uses solo).

**Comment by stajkowski** [comment]
This is fixed, the latest version of hostupgrade allows for chef-solo flag(tmp file) for first time run only.  This does a check to see if chef-solo is running, and if so, use a file flag instead of saving the node to chef-server.  You can now use the latest versions of both php5-fpm and hostupgrade with chef-solo.

**Comment by mike-spainhower** [comment]
You are awesome :clap: Thank you!

Confirmed this fixed the issue with `kitchen-ec2`
