### ISSUE TITLE
Some options in php5_fpm_pool not being overwritten

### ISSUE THREAD

**Issue by codedbypaul** [stajkowski/php5-fpm#9]
Just noticed that if I specify listen_owner, listen_group or listen_mode in php_fpm_pool  they aren't being set in he generated conf file.
Here's my settings:
```
php5_fpm_pool "www" do
	pool_user "www-data"
	pool_group "www-data"
	listen_address "127.0.0.1"
	listen_port 9000
	listen_owner = "www-data"
	listen_group = "www-data"
	listen_mode = "0666"
	overwrite true
	action :create
end
```
But I end up with
```
[www]
###### Base Pool Configuration
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.owner =
listen.group =
listen.mode =
listen.backlog = 65536
```

**Comment by stajkowski** [comment]
Ok I'll look into this!

**Comment by stajkowski** [comment]
Hey there's just an error in your resource block.  Just saw this now.  Change:

php5_fpm_pool "www" do
    pool_user "www-data"
    pool_group "www-data"
    listen_address "127.0.0.1"
    listen_port 9000
    listen_owner = "www-data"
    listen_group = "www-data"
    listen_mode = "0666"
    overwrite true
    action :create
end

To

php5_fpm_pool "www" do
    pool_user "www-data"
    pool_group "www-data"
    listen_address "127.0.0.1"
    listen_port 9000
    listen_owner "www-data"
    listen_group "www-data"
    listen_mode "0666"
    overwrite true
    action :create
end

Then you should be good to go!  Thanks!

**Comment by stajkowski** [comment]
Complete
